version: '3.7'
services:
    mysql:
        container_name: mysql
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./db-data:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: Q9mI4GpnjuAa
        networks:
            - webnet
        restart: always

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql
        networks:
            - webnet
        restart: always

    # airline:
    #     container_name: airline_api
    #     image: airline
    #     build:
    #       context: .
    #       dockerfile: Dockerfile
    #     restart: on-failure
    #     volumes:
    #       - .:/airline
    #     ports:
    #       - 8081:8081
    #     environment:
    #         SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Faber?autoReconnect=true&useSSL=false
    #     links:
    #       - mysql
    #     networks:
    #         - webnet
networks:
    webnet:
        name: webnet
        driver: bridge
